### ISSUE TITLE
problem：“KeyError: 'Seq'”, it sound like the dataset has some problems, how should l solve the problem?

### ISSUE THREAD

**Issue by LIUYellowBlack** [ZhaohanM/FusionDTI#2]
(FusionDTI) PS D:\FusionDTI> python main_token.py --dataset BindingDB
Traceback (most recent call last):
  File "C:\xxxxx\anaconda3\envs\FusionDTI\lib\site-packages\pandas\core\indexes\base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Seq'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main_token.py", line 312, in <module>
    train_files, valid_files, test_files = encode_pretrained_feature(args)
  File "main_token.py", line 188, in encode_pretrained_feature
    Dataset = DatabaseProcessor(args)
  File "D:\FusionDTI\utils\process_datasets.py", line 41, in __init__
    self.train_dataset_df["Seq"].values,
  File "C:\xxxxx\anaconda3\envs\FusionDTI\lib\site-packages\pandas\core\frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\xxxx\anaconda3\envs\FusionDTI\lib\site-packages\pandas\core\indexes\base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'Seq'
Exception in thread IntMsgThr:
Traceback (most recent call last):
  File "C:\xxxxx\anaconda3\envs\FusionDTI\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\xxxx\anaconda3\envs\FusionDTI\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\xxxx\anaconda3\envs\FusionDTI\lib\site-packages\wandb\sdk\wandb_run.py", line 325, in check_internal_messages
    self._loop_check_status(
  File "C:\xxxx\anaconda3\envs\FusionDTI\lib\site-packages\wandb\sdk\wandb_run.py", line 235, in _loop_check_status
    local_handle = request()
  File "C:\xxxx\anaconda3\envs\FusionDTI\lib\site-packages\wandb\sdk\interface\interface.py", line 914, in deliver_internal_messages
    return self._deliver_internal_messages(internal_message)
  File "C:\xxxx\anaconda3\envs\FusionDTI\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 503, in _deliver_internal_messages
    return self._deliver_record(record)
  File "C:\xxxx\anaconda3\envs\FusionDTI\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 452, in _deliver_record
    handle = mailbox._deliver_record(record, interface=self)
  File "C:\xxxx\anaconda3\envs\FusionDTI\lib\site-packages\wandb\sdk\lib\mailbox.py", line 451, in _deliver_record
    interface._publish(record)
  File "C:\xxxx\anaconda3\envs\FusionDTI\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\xxxx\anaconda3\envs\FusionDTI\lib\site-packages\wandb\sdk\lib\sock_client.py", line 225, in send_record_publish
    self.send_server_request(server_req)
  File "C:\xxxx\anaconda3\envs\FusionDTI\lib\site-packages\wandb\sdk\lib\sock_client.py", line 157, in send_server_request
    self._send_message(msg)
  File "C:\xxxx\anaconda3\envs\FusionDTI\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\xxxx\anaconda3\envs\FusionDTI\lib\site-packages\wandb\sdk\lib\sock_client.py", line 132, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionAbortedError: [WinError 10053] 你的主机中的软件中止了一个已建立的连接。
wandb: 🚀 View run decent-mountain-36 at: https://wandb.ai/xxxx/DTI_Prediction_with_Token-level_Fusion/runs/ari4advu
wandb: Find logs at: wandb\xxxx\logs

looking forward to your reply

**Comment by ZhaohanM** [comment]
Thank you for your interest in our work. 

Please check the header of the protein structure-aware sequence in the datasets you obtained. The reported error shows that the protein's header is not ‘Seq’ in the datasets. Furthermore, the original BindingDB, BioSNAP, and Human Datasets cannot be used directly, as you need to convert them to the structure-aware sequence of proteins and the SELFIES of drugs according to the guidelines. 

<img width="839" alt="image" src="https://github.com/user-attachments/assets/99e16b5b-7a7c-4537-a532-6aee4c0aded3">

**Comment by LIUYellowBlack** [comment]
Okay, thank you for your response. It is very helpful.

**Comment by LIUYellowBlack** [comment]
I am facing challenges in resolving the "keyword:seq" issue and, once again.
I find myself in need of your expertise. Please accept my apologies for the repeated request, and I thank you in advance for your continued support.
I have successfully obtained the Alpha_seq.csv and Alpha_stru_seq.csv files, in addition to the SELFIES dataset. Although I have previously received guidance, I must admit that I remain somewhat perplexed about the proper sequence of actions for initiating the training process.

**Comment by ZhaohanM** [comment]
> I am facing challenges in resolving the "keyword:seq" issue and, once again. I find myself in need of your expertise. Please accept my apologies for the repeated request, and I thank you in advance for your continued support. I have successfully obtained the Alpha_seq.csv and Alpha_stru_seq.csv files, in addition to the SELFIES dataset. Although I have previously received guidance, I must admit that I remain somewhat perplexed about the proper sequence of actions for initiating the training process.

Congratulations on obtaining the SELFIES dataset and the structure-aware sequences of proteins! 
The next logical step is to integrate these datasets with established benchmarks like BindingDB, BioSNAP, or even your customised dataset. This alignment will enable you to set up the training process effectively. Here's an example dataset for guidance:

<img width="924" alt="image" src="https://github.com/user-attachments/assets/fbbe491e-f54d-4d94-923e-92eaf0f70957">

**Comment by LIUYellowBlack** [comment]
Mr. Zhaohan,

I am truly grateful for the time you took to respond in detail to my questions. Your patience and kindness in addressing each of my queries are especially valuable. 

Your expert guidance has significantly enhanced my understanding of the two pre-trained models, and it is thanks to your assistance that my model training was able to be completed successfully.

I am immensely thankful for your selfless support and careful mentorship!

![image](https://github.com/user-attachments/assets/db0e0a22-5a90-4382-877c-c7c0af12ab04)

**Comment by ZhaohanM** [comment]
Thank you for your kind words. I'm truly glad to hear that my guidance was helpful and that your model training was successful. Wishing you continued success in your work!
